/* Enhanced DB2 SQL Example with Comprehensive Business Rules */

/* Data Integrity Rules */
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    STATUS CHAR(1) DEFAULT 'A',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('A', 'I', 'D')),
    CONSTRAINT CHK_EMAIL CHECK (EMAIL LIKE '%@%')
);

CREATE TABLE ORDERS (
    ORDER_ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    AMOUNT DECIMAL(9,2) NOT NULL,
    TAX_AMOUNT DECIMAL(9,2),
    TOTAL_AMOUNT DECIMAL(9,2),
    STATUS CHAR(1) DEFAULT 'P',
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) 
        REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT CHK_AMOUNT CHECK (AMOUNT > 0),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('P', 'C', 'X'))
);

CREATE TABLE ORDER_ITEMS (
    ITEM_ID INTEGER PRIMARY KEY,
    ORDER_ID INTEGER NOT NULL,
    PRODUCT_CODE VARCHAR(20) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(9,2) NOT NULL,
    LINE_TOTAL DECIMAL(9,2),
    CONSTRAINT FK_ITEM_ORDER FOREIGN KEY (ORDER_ID) 
        REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT CHK_QUANTITY CHECK (QUANTITY > 0),
    CONSTRAINT CHK_PRICE CHECK (UNIT_PRICE > 0)
);

/* Business Rule Triggers */
CREATE TRIGGER VALIDATE_ORDER_TOTAL
BEFORE INSERT ON ORDERS
REFERENCING NEW AS N
FOR EACH ROW
BEGIN
    DECLARE v_tax DECIMAL(9,2);
    DECLARE v_total DECIMAL(9,2);
    
    -- Business Calculation Rule
    SET v_tax = N.AMOUNT * 0.07;
    SET v_total = N.AMOUNT + v_tax;
    
    -- Data Validation Rule
    IF v_total > 99999.99 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Order total exceeds maximum limit';
    END IF;
    
    SET N.TAX_AMOUNT = v_tax;
    SET N.TOTAL_AMOUNT = v_total;
END;

CREATE TRIGGER UPDATE_CUSTOMER_STATUS
AFTER UPDATE ON ORDERS
REFERENCING NEW AS N
FOR EACH ROW
BEGIN
    -- Business Logic Rule
    IF N.STATUS = 'C' THEN
        UPDATE CUSTOMERS 
        SET STATUS = 'A' 
        WHERE CUSTOMER_ID = N.CUSTOMER_ID;
    END IF;
END;

/* Stored Procedure Business Rules */
CREATE PROCEDURE CALCULATE_ORDER_DISCOUNT(
    IN p_customer_id INTEGER,
    OUT p_discount_rate DECIMAL(5,4)
)
LANGUAGE SQL
BEGIN
    DECLARE v_total_orders INTEGER;
    DECLARE v_total_amount DECIMAL(12,2);
    
    -- Business Calculation Rule
    SELECT COUNT(*), SUM(TOTAL_AMOUNT)
    INTO v_total_orders, v_total_amount
    FROM ORDERS
    WHERE CUSTOMER_ID = p_customer_id
    AND STATUS = 'C';
    
    -- Business Rule Logic
    IF v_total_amount > 10000 THEN
        SET p_discount_rate = 0.15;
    ELSEIF v_total_amount > 5000 THEN
        SET p_discount_rate = 0.10;
    ELSEIF v_total_amount > 1000 THEN
        SET p_discount_rate = 0.05;
    ELSE
        SET p_discount_rate = 0.00;
    END IF;
END;

/* Access Control Rules */
CREATE ROLE ORDER_CLERK;
CREATE ROLE ORDER_MANAGER;
CREATE ROLE ORDER_ADMIN;

GRANT SELECT, INSERT ON ORDERS TO ORDER_CLERK;
GRANT SELECT, UPDATE ON ORDERS TO ORDER_MANAGER;
GRANT ALL PRIVILEGES ON ORDERS TO ORDER_ADMIN;

GRANT SELECT ON CUSTOMERS TO ORDER_CLERK;
GRANT SELECT, UPDATE ON CUSTOMERS TO ORDER_MANAGER;
GRANT ALL PRIVILEGES ON CUSTOMERS TO ORDER_ADMIN;

/* Business Calculation Views */
CREATE VIEW ORDER_SUMMARY AS
SELECT 
    O.ORDER_ID,
    C.CUSTOMER_NAME,
    O.ORDER_DATE,
    O.AMOUNT,
    O.TAX_AMOUNT,
    O.TOTAL_AMOUNT,
    CASE 
        WHEN O.TOTAL_AMOUNT > 1000 THEN 'HIGH'
        WHEN O.TOTAL_AMOUNT > 500 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ORDER_PRIORITY,
    CASE 
        WHEN O.STATUS = 'P' THEN 'PENDING'
        WHEN O.STATUS = 'C' THEN 'COMPLETED'
        WHEN O.STATUS = 'X' THEN 'CANCELLED'
    END AS STATUS_DESC
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID;

/* Data Validation Function */
CREATE FUNCTION VALIDATE_ORDER_AMOUNT(p_amount DECIMAL(9,2))
RETURNS BOOLEAN
LANGUAGE SQL
BEGIN
    -- Business Validation Rule
    IF p_amount <= 0 THEN
        RETURN FALSE;
    END IF;
    
    IF p_amount > 99999.99 THEN
        RETURN FALSE;
    END IF;
    
    RETURN TRUE;
END;
