-- DB2 SQL example
CREATE TABLE CUSTOMER (
  CUSNUM DECIMAL(7,0) NOT NULL,
  CUSNAM CHAR(50),
  BALDUE DECIMAL(11,2)
);

CREATE VIEW V_CUSTOMER AS
  SELECT CUSNUM, CUSNAM, BALDUE FROM CUSTOMER;

SELECT * FROM CUSTOMER WHERE CUSNUM = 12345;

INSERT INTO CUSTOMER (CUSNUM, CUSNAM, BALDUE) VALUES (1, 'ACME', 0);
